name: Deploy to Firebase

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Execute Gradle command - assembleDebug
        run: ./gradlew assembleDebug

      - name: Upload Artifact to Firebase App Distribution
        uses: actions/upload-artifact@v3.1.3
        with:
          name:
            AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk
